config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :tasks
  end

  resources :tasks do
    resources :comments, only: [:new, :create]
  end

  resource :profile, only:[:show, :edit, :update] #プロフィールは1つしかないはずなので[resource]の単数になる
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    has_one_attached :eyecatch
    belongs_to :user
    has_many :tasks, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :task
    belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    has_one_attached :avatar
end

app/models/task.rb
class Task < ApplicationRecord
    has_one_attached :eyecatch
    belongs_to :user
    belongs_to :board
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def avatar_image
    'default-avatar.png'
  end

  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :commnets, dependent: :destroy
  has_one :profile, dependent: :destroy

  def prepare_profile
    Profile || build_profile
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @boards = Board.all
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to root_path, notice: '保存できました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end


  def show
    @board = Board.find(params[:id])
    @tasks = @board.tasks
    # /boards/:id(.:format)
  end

  def edit
    # /boards/:id/edit(.:format)
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board), notice:'更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    board = Board.find(params[:id])
    board.destroy!
    redirect_to root_path, notice:'削除できました'
  end


  private

  def board_params
    params.require(:board).permit(:name, :description, :eyecatch)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    def new
        @task = Task.find(params[:task_id])
        @comment = @task.comments.build
    end

    def create
        @task = Task.find(params[:task_id])
        @comment = @task.comments.build(comment_params)
        @comment.user_id = current_user.id
        if @comment.save
            redirect_to board_task_path(board_id: @task.board_id, id: @task.id), notice:'コメント追加'
        else
            flash.now[:error] = '保存に失敗しました'
            render :new
        end
    end


    private
    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!


    def show
      @profile = current_user.profile #profile(単数)＝ model#profile.rbと紐づけられる
    end

    def edit
      @profile = current_user.build_profile #has_oneの時はbuild_profileにする(#current_user.boards.buildはhas_manyのとき)
    end

    def update
      @profile = current_user.build_profile(profile_params)
      if @profile.save
        redirect_to profile_path, notice: 'プロフィールを更新しました'
      else
        flash.now[:error] = '更新に失敗しました'
        render :edit
      end
    end

    private
    def profile_params
      params.require(:profile).permit(:avatar, :nickname)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    
    def index
        @tasks = Task.all
    end

    def new
        board = Board.find(params[:board_id])
        @task = board.tasks.build
        @task.user_id = current_user.id
    end

    def create
        board = Board.find(params[:board_id])
        @task = board.tasks.build(task_params)
        @task.user_id = current_user.id
        if @task.save
            redirect_to board_path(board), notice: 'タスクを追加'
        else
            flash.now[:eroor] = '更新できませんでした'
            render :new
        end
    end

    def show
        @task = Task.find(params[:id])
        @board = @task.board
        @comments = @task.comments
    end

    def edit
        @task = Task.find(params[:board_id])
        @board = @task.board
    end

    def update
        @task = Task.find(params[:board_id])
        @board = @task.board
        if @task.update(task_params)
            redirect_to board_path(@board.id), notice: '更新できました'
        else
            flash.now[:error] = '失敗しました'
            render :edit
        end
    end

    def destroy
        task = Task.find(params[:id])
        @board = task.board
        task.destroy!
        redirect_to root_path, notice: '削除に成功しました'
    end


    private
    def task_params
        params.require(:task).permit(:title, :content, :eyecatch, :deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.haml
# .container
# %ul
# - board.errors.full_messages.each do |message|
#     %li= message    
#     = form_with(model:@board, url:board_path(@board),method:'put', local: true) do |f|
#     %div
#         = f.label :name, 'Name'
#     %div
#         = f.text_field :name, class: 'text'
#     %div
#         = f.label :description, 'Description'
#     %div
#         = f.text_area :description, class:'text'
#     %div
#         = f.submit 'Submit', class: 'btn-primary'

app/views/boards/edit.html.haml
.container
  %p.header_text
  = form_with(model: @board,url: board_path, method: 'put',local: true) do |f| 
    %div
      = f.label :name, 'タイトル'
    %div
      = f.text_field :name, class: 'text'
    %div
      = f.label :description, '概要'
    %div
      = f.text_area :description, class: 'board-area'
    = f.submit '保存' ,class: 'btn-primary'

app/views/boards/index.html.haml
.container
  %h2 All Boards
  - @boards.each do|board|
    = link_to board_path(board) do
      .card
        .card_name
          = board.name
        .card_description
          = board.description
          
  .card_add
    = link_to '+ Add new board ', new_board_path 

app/views/boards/new.html.haml
.container
  %p.header_text
  .border_line
  %h2 New Board
  = form_with(model: @board,url: boards_path, method: 'post',local: true) do |f| 
    %div
      = f.label :name, 'タイトル'
    %div
      = f.text_field :name, class: 'text'
    %div
      = f.label :description, '概要'
    %div
      = f.text_area :description, class: 'board-area'
    = f.submit '保存' ,class: 'btn-primary'

app/views/boards/show.html.haml
.container
  %p.header_text
  .border_line
  .card
    %h2= @board.name
    %p= @board.description
    .dropdown
      = image_tag 'actions.svg', class: 'dropbtn'
      .dropdown-content.mini
        = link_to '編集' , edit_board_path(@board)
        = link_to '削除' , board_path(@board), data: { method: 'delete' , confirm: '本当に削除してもよろしいですか？' }

  %h2 タスク一覧
  - @tasks.each do |task|
    = link_to board_task_path(@board.id, task.id) do
      .card
        %h2= task.title
        %p= task.content

  .card_add
    = link_to '+ Add new card ', new_board_task_path(@board)

app/views/comments/new.html.haml
.container
  = form_with(model: @comment, url: task_comments_path(@task), method: 'post', local: true) do |f|
    %div
      = f.label :content, 'コメント'
    %div
      = f.text_area :content, class: 'board-area'
    = f.submit '保存' ,class: 'btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApp2
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          = link_to :back do
            = image_tag 'default-avatar.png', class: 'header_back'
        %p.header_pageTitle 
          = link_to 'Boards', root_path
      - if user_signed_in?
        .dropdown_icon
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content_icon
            = link_to 'プロフィール', profile_path
            = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
      - else
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
          
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/profiles/edit.html.haml
.container
  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div
      = f.label :avatar, 'アバター'
    %div
      = f.file_field :avatar
    %div
      = f.label :nickname, 'ニックネーム'
    %div
      = f.text_field :nickname, class: 'text'
    %div
    = f.submit '保存', class: 'btn-primary'

app/views/profiles/show.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_image
      = image_tag current_user.avatar_image
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_actionButton
          = link_to 'Edit', edit_profile_path
      .profilePage_user_introduction
        = current_user.profile&.introduction

app/views/tasks/edit.html.haml
.container
  %p.header_text
  = form_with(model: @task,url: board_task_path, method: 'put',local: true) do |f| 
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '概要'
    %div
      = f.text_area :content, class: 'board-area'
    = f.submit '保存' ,class: 'btn-primary'

app/views/tasks/index.html.haml
%h2 インデックス

app/views/tasks/new.html.haml
.container
  %p.header_text
  .border_line
  %h2 New Card
  = form_with(model: @task,url: board_tasks_path(@task.board), method: 'post',local: true) do |f| 
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '概要'
    %div
      = f.text_area :content, class: 'board-area'
    = f.submit '保存' ,class: 'btn-primary'

app/views/tasks/show.html.haml
.container
  %p.header_text
  .border_line
  .card
    %h2= @task.title
    %p= @task.content
    .dropdown
      = image_tag 'actions.svg', class: 'dropbtn'
      .dropdown-content.mini
        = link_to '編集' , edit_board_task_path(@task,@board)
        = link_to '削除' , board_task_path(@board,@task), data: { method: 'delete' , confirm: '本当に削除してもよろしいですか？' }
 
  %h2 コメント一覧
  - @comments.each do |comment|
    = link_to new_task_comment_path(@board,@task) do
      .comment
        %p= comment.content

  .card_add
    = link_to '+ New Comment', new_task_comment_path(@task)